name: test
on:
  workflow_dispatch: {}
  push:
   branches:
     - main
     - master
 
jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test added-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changed-files
        name: Check changed files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.txt
      - id: print
        name: Print
        shell: bash
        run: |
          cat <<EOF
          ${{ steps.changed-files.outputs }}
          EOF
